CREATE TABLE IF NOT EXISTS `house_furniture` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `house_id` VARCHAR(50) NOT NULL,
  `model` BIGINT(20) NOT NULL, 
  `x` DOUBLE NOT NULL,
  `y` DOUBLE NOT NULL,
  `z` DOUBLE NOT NULL,
  `rx` DOUBLE NOT NULL,
  `ry` DOUBLE NOT NULL,
  `rz` DOUBLE NOT NULL,
  `collision` TINYINT(1) DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;